// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelDeletion cancels an ongoing deletion
 * @returns {$CancellablePromise<void>}
 */
export function CancelDeletion() {
    return $Call.ByID(2814260365);
}

/**
 * GetLiveMetrics returns current deletion metrics
 * @returns {$CancellablePromise<$models.LiveMetrics>}
 */
export function GetLiveMetrics() {
    return $Call.ByID(3236582694).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Name returns the service name
 * @returns {$CancellablePromise<string>}
 */
export function Name() {
    return $Call.ByID(257522798);
}

/**
 * OnShutdown is called when the app is shutting down
 * Security: Edge case handling for window close during deletion
 * @returns {$CancellablePromise<void>}
 */
export function OnShutdown() {
    return $Call.ByID(999779538);
}

/**
 * OnStartup is called when the app is starting up
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup(options) {
    return $Call.ByID(2232168041, options);
}

/**
 * ScanDirectory scans a directory and returns file counts
 * @param {$models.Config} config
 * @returns {$CancellablePromise<$models.ScanResult>}
 */
export function ScanDirectory(config) {
    return $Call.ByID(971567811, config).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SetApp sets the application instance
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(4256893662, app);
}

/**
 * StartDeletion begins the deletion process
 * @param {$models.Config} config
 * @returns {$CancellablePromise<void>}
 */
export function StartDeletion(config) {
    return $Call.ByID(4274926953, config);
}

/**
 * ValidatePath validates if a path is safe to delete
 * @param {string} path
 * @returns {$CancellablePromise<$models.ValidationResult>}
 */
export function ValidatePath(path) {
    return $Call.ByID(1066317236, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LiveMetrics.createFrom;
const $$createType1 = $models.ScanResult.createFrom;
const $$createType2 = $models.ValidationResult.createFrom;
