// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds the configuration for deletion operations
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("targetDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetDir"] = "";
        }
        if (!("force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["force"] = false;
        }
        if (!("dryRun" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dryRun"] = false;
        }
        if (!("verbose" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["verbose"] = false;
        }
        if (!("logFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logFile"] = "";
        }
        if (!("keepDays" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["keepDays"] = null;
        }
        if (!("workers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workers"] = 0;
        }
        if (!("bufferSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bufferSize"] = 0;
        }
        if (!("deletionMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deletionMethod"] = "";
        }
        if (!("benchmark" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["benchmark"] = false;
        }
        if (!("monitor" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["monitor"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * LiveMetrics holds real-time deletion metrics
 */
export class LiveMetrics {
    /**
     * Creates a new LiveMetrics instance.
     * @param {Partial<LiveMetrics>} [$$source = {}] - The source object to create the LiveMetrics.
     */
    constructor($$source = {}) {
        if (!("filesDeleted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filesDeleted"] = 0;
        }
        if (!("deletionRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["deletionRate"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SystemMetrics | null | undefined}
             */
            this["systemMetrics"] = undefined;
        }
        if (!("elapsedSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsedSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LiveMetrics}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("systemMetrics" in $$parsedSource) {
            $$parsedSource["systemMetrics"] = $$createField2_0($$parsedSource["systemMetrics"]);
        }
        return new LiveMetrics(/** @type {Partial<LiveMetrics>} */($$parsedSource));
    }
}

/**
 * ScanResult holds the result of directory scanning
 */
export class ScanResult {
    /**
     * Creates a new ScanResult instance.
     * @param {Partial<ScanResult>} [$$source = {}] - The source object to create the ScanResult.
     */
    constructor($$source = {}) {
        if (!("totalScanned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalScanned"] = 0;
        }
        if (!("totalToDelete" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalToDelete"] = 0;
        }
        if (!("totalRetained" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalRetained"] = 0;
        }
        if (!("totalSizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalSizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult(/** @type {Partial<ScanResult>} */($$parsedSource));
    }
}

/**
 * SystemMetrics holds system resource usage data
 */
export class SystemMetrics {
    /**
     * Creates a new SystemMetrics instance.
     * @param {Partial<SystemMetrics>} [$$source = {}] - The source object to create the SystemMetrics.
     */
    constructor($$source = {}) {
        if (!("cpuPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuPercent"] = 0;
        }
        if (!("memoryMb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memoryMb"] = 0;
        }
        if (!("ioOpsPerSec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ioOpsPerSec"] = 0;
        }
        if (!("goroutineCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["goroutineCount"] = 0;
        }
        if (!("memoryPressure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["memoryPressure"] = false;
        }
        if (!("gcPressure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["gcPressure"] = false;
        }
        if (!("cpuSaturated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cpuSaturated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemMetrics(/** @type {Partial<SystemMetrics>} */($$parsedSource));
    }
}

/**
 * ValidationResult holds the result of path validation
 */
export class ValidationResult {
    /**
     * Creates a new ValidationResult instance.
     * @param {Partial<ValidationResult>} [$$source = {}] - The source object to create the ValidationResult.
     */
    constructor($$source = {}) {
        if (!("isValid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isValid"] = false;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidationResult(/** @type {Partial<ValidationResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SystemMetrics.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
